//  these variables are used within the modules
DIMENSION_CENTER = 0;
DIMENSION_LEFT = 1;
DIMENSION_RIGHT = 2;
DIMENSION_OUTSIDE = 3;
DIMENSION_ABOVE = 4;
DIMENSION_UNDER = 5;
DIMENSION_HORZ = 0;
DIMENSION_VERT = 1;
DIMENSION_UPPER_LEFT = 0;
DIMENSION_UPPER_RIGHT = 1;
DIMENSION_LOWER_LEFT = 2;
DIMENSION_LOWER_RIGHT = 3;

